var:
  nacos:
    addr: test.nacos.hifor.net:8848
    username: nacos-sample
    password: "Ry*UuP6#k$VE^BLr"
    namespace: de16af61-c5b9-41ec-b594-6c7e88bb57ca
    group: sample-group
  java-home: ${JAVA_HOME:empty}

var-application-yml: hahalala

server:
  #default port 8080
  port: 8080
nacos:
  config:
    bootstrap:
      enable: true
    server-addr: ${var.nacos.addr}
    context-path: /nacos
    username: ${var.nacos.username}
    password: ${var.nacos.password}
    namespace: ${var.nacos.namespace}
    data-ids: nacos-config-a.yml,nacos-config-b.yml
    group: ${var.nacos.group}
    auto-refresh: true


#    server-addr: test.hifor.net:80
#    username: nacos
#    password: nacos
#    namespace: cbf9f8f3-3f47-4eb1-8aec-fd635032e43c
#    data-ids: test.yml,config-common.yml
#    group: HI-SPRINGBOOT
#    auto-refresh: true

#    ext-config:
#      - data-id: config-common.yml
#        group: HI-SPRINGBOOT
#        type: yaml
#        auto-refresh: true


# ------------ nacos config ------------
# reeources/nacos/*.yml